name: Deploy to cPanel FTP

on:
  push:
    branches:
      - main  # ganti jika perlu

jobs:
  ftp-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload to cPanel via FTP
        env:
          FTP_HOST: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
          FTP_DIR: ${{ secrets.FTP_DIR }}
        run: |
          lftp -e "
          set ftp:ssl-allow no;
          mirror -R --delete --verbose ./ $FTP_DIR;
          bye" -u "$FTP_USER","$FTP_PASS" "$FTP_HOST"
